const columnEn = {
  complaintRisk: 'complaintRisk',
  priority: 'priority',
  caseTag: 'label',
  workOrderCode: 'case number',
  batchCode: 'batch code',
  batchName: 'batch name',
  entrustTenantName: 'asset party',
  owobsn: 'asset party batch',
  owosn: 'asset party number',
  productName: 'product name',
  customerName: 'name',
  idCard: 'id card',
  phone: 'phone',
  numberDetectionFlag: 'number is detected',
  entrustAmount: 'entrust amount',
  entrustBalance: 'entrust balance',
  confirmRepaymentAmount: 'confirmRepaymentAmount',
  followUpTime: 'followUpTime',
  collectionRecordStatus: 'collectionRecordStatus',
  overdueDays: 'overdue days',
  overdueStage: 'overdue stage',
  repaymentAmount: 'cp amount',
  lastPtpAmount: 'PTP amount',
  totalAmountRepayment: 'total amount repaid',
  caseType: 'case type',
  caseStatus: 'case status',
  repaymentStatus: 'repayment status',
  reduceStatus: 'reduce status',
  retainStatus: 'retain status',
  retainTimes: 'retain times',
  retainDays: 'retain days',
  entrustStartTime: 'entrust time',
  entrustReturnTime: 'entrust return time',
  entrustDays: 'entrust days',
  assignByName: 'assign name',
  belongTenantName: 'workplace',
  belongOrgName: 'workplace department',
  belongOrgTime: 'belongOrgTime',
  belongUserInfoName: 'belongUserInfoName',
  belongUserInfoTime: 'belongUserInfoTime',
  lastCallTime: 'last call time',
  remark: 'remark',
  wodStatus: 'wod status',
  createSMSTask: 'create SMS task',
  fileTemplate: 'generate lawyer letter in batch',
  case: 'case',
  recoveryTime: 'recoveryTime',
  score: 'score',
  lateCharge: '案件罚息'
}
const columnZh = {
  complaintRisk: '投诉风险',
  priority: '优先级',
  caseTag: '标签',
  workOrderCode: '案件编号',
  batchCode: '批次号',
  batchName: '批次名称',
  entrustTenantName: '资产方',
  owobsn: '资产方批次号',
  owosn: '资产方个案号',
  productName: '产品名称',
  customerName: '姓名',
  idCard: '证件号码',
  phone: '手机号',
  numberDetectionFlag: '号码是否检测',
  entrustAmount: '委案金额',
  entrustBalance: '委案余额',
  confirmRepaymentAmount: '确认还款金额',
  followUpTime: '最近一次跟进时间',
  collectionRecordStatus: '催记跟进状态',
  overdueDays: '逾期天数',
  overdueStage: '逾期阶段',
  repaymentAmount: 'CP金额',
  lastPtpAmount: 'PTP金额',
  totalAmountRepayment: '已还款总金额',
  caseType: '案件类型',
  caseStatus: '案件状态',
  repaymentStatus: '还款状态',
  reduceStatus: '减免状态',
  retainStatus: '留案状态',
  retainTimes: '留案次数',
  retainDays: '留案延期天数',
  entrustStartTime: '委案时间',
  entrustReturnTime: '退案时间',
  entrustDays: '委案天数',
  assignByName: '分配人',
  belongTenantName: '职场',
  belongOrgName: '职场部门',
  belongOrgTime: '分配部门时间',
  belongUserInfoName: '催收员',
  belongUserInfoTime: '分配催员时间',
  lastCallTime: '最后通话时间',
  remark: '备注',
  wodStatus: '案件阶段',
  createSMSTask: '创建短信任务',
  fileTemplate: '批量生成律师函',
  case: '案件',
  recoveryTime: '回收时间',
  score: '评分',
  lateCharge: '案件罚息'
}
export default {
  en: {
    ...columnEn,
    repayment: 'repayment',
    belongOrgId: 'department',
    belongUserInfoId: 'staff'
  },
  zh: {
    ...columnZh,
    repayment: '还款',
    belongOrgId: '部门',
    belongUserInfoId: '催员'
  }
}
