export default {
  en: {
    jobNo: 'job No',
    extension: 'extension',
    agentStatus: 'agent status',
    userStatus: 'user status',
    moveIn: 'move in',
    moveOut: 'move out',
    number: 'number',
    task: 'task',
    idle: 'idle',
    dialing: 'dialing',
    incomingCall: 'incoming call',
    calling: 'calling',
    offline: 'offline',
    activeing: 'active',
    hangup: 'hangup',
    answer: 'answer',
    stopAutoCall: 'stop auto call',
    reCheckIn:
      'The current agent has logged in to another terminal. Do you want to check in again?',
    continueMoveIn: 'continue move in',
    cancelMoveIn: 'canel move in',
    confirmDisconnect: 'confirm disconnect?',
    notVacantAgent: 'no vacant seats',
    queueEnd: 'Call queue ended',
    nextFail: 'next fail!'
  },
  zh: {
    jobNo: '工号',
    extension: '坐席',
    agentStatus: '坐席状态',
    userStatus: '员工状态',
    moveIn: '已签入',
    moveOut: '已签出',
    number: '号码',
    task: '任务',
    idle: '空闲中',
    dialing: '拨打中',
    incomingCall: '来电振铃中',
    calling: '接通中',
    offline: '坐席离线',
    activeing: '启用中',
    hangup: '挂断',
    answer: '接听',
    stopAutoCall: '暂停自动外呼',
    reCheckIn: '当前坐席已经在其他终端登录,是否重新签入?',
    continueMoveIn: '继续签入',
    cancelMoveIn: '取消签入',
    confirmDisconnect: '确定签出?',
    notVacantAgent: '暂无空闲坐席',
    queueEnd: '呼叫队列已结束',
    nextFail: '自动拨打下一条失败!'
  }
}
