/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CallToolbar: typeof import('./src/components/home-layout/components/nav-bar/components/call-toolbar/index.vue')['default']
    ChantOperation: typeof import('./src/components/chant-operation/index.vue')['default']
    ChantPagination: typeof import('./src/components/ChantPagination.vue')['default']
    ChantTable: typeof import('./src/components/ChantTable.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FieldFilter: typeof import('./src/components/chant-operation/components/FieldFilter.vue')['default']
    HomeLayout: typeof import('./src/components/home-layout/index.vue')['default']
    Iconfont: typeof import('./src/components/Iconfont.vue')['default']
    IconFont: typeof import('./src/components/IconFont.vue')['default']
    NavBar: typeof import('./src/components/home-layout/components/nav-bar/index.vue')['default']
    NavMenu: typeof import('./src/components/home-layout/components/NavMenu.vue')['default']
    NavTab: typeof import('./src/components/home-layout/components/NavTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemNotice: typeof import('./src/components/home-layout/components/nav-bar/components/SystemNotice.vue')['default']
    TableOperation: typeof import('./src/components/chant-operation/components/TableOperation.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
