export default {
  en: {
    please: 'please ',
    notData: 'please selected data',
    assignType: 'assign type',
    ccWorkplaceBizType: 'ccWorkplaceBizType',
    transferType: 'transfer type',
    assignPreference: 'assign preference',
    workplace: 'workplace',
    department: 'department',
    personal: 'personal',
    employee: 'employee',
    to: 'to',
    employeeAccount: 'employee account',
    employeeName: 'employee name',
    assignStockFlag: 'whether to consider stock',
    totalCaseNum: 'case num',
    totalEntrustAmount: 'case total amount',
    assignable: 'assignable ',
    transferable: 'transferable ',
    assigned: 'assigned ',
    transfered: 'transfered ',
    repeat: 'cannot select duplicate employees'
  },
  zh: {
    please: '请先',
    notData: '请先选择数据',
    assignType: '分配方式',
    ccWorkplaceBizType: '职场业务类型',
    transferType: '转移方式',
    assignPreference: '分配偏好',
    workplace: '职场',
    department: '部门',
    personal: '个人',
    employee: '员工',
    to: '到',
    employeeAccount: '员工账号',
    employeeName: '员工姓名',
    assignStockFlag: '是否考虑存量',
    totalCaseNum: '案件数',
    totalEntrustAmount: '委案总金额',
    assignable: '可分配',
    transferable: '可转移',
    assigned: '已分配',
    transfered: '已转移',
    repeat: '不能选择重复的员工'
  }
}
