export default {
  en: {
    ctsn: 'ctsn',
    taskSn: 'task sn',
    taskType: 'task type',
    userInfoId: 'user info id',
    userInfoName: 'user info name',
    name: 'name',
    batchId: 'batch id',
    batchOrder: 'batch order',
    year: 'year',
    month: 'month',
    date: 'date',
    dateHour: 'date hour',
    hour: 'hour',
    callSys: 'call sys',
    createType: 'create type',
    businessScenario: 'business scenario',
    industryCode: 'industry code',
    taskClassify: 'task classify',
    status: 'status',
    editStatus: 'edit status',
    statusFailType: 'status fail type',
    failReason: 'fail reason',
    isForcibly: 'is forcibly',
    autoDedup: 'auto dedup',
    smsSendFlag: 'sms send flag',
    hangupSmsId: 'hangup sms id',
    hangupSmsName: 'hangup sms name',
    totalCount: 'total count',
    formalCount: 'formal count',
    testCount: 'test count',
    addDataSuccCount: 'add data succ count',
    addDataFailCount: 'add data fail count',
    processCount: 'process count',
    cancelCallCount: 'cancel call count',
    blackListCount: 'black list count',
    dedupCount: 'dedup count',
    succSyncCount: 'succ sync count',
    succSyncRate: 'succ sync rate',
    connCount: 'conn count',
    connRate: 'conn rate',
    totalTalkingTime: 'total talking time',
    maxTalkingTime: 'max talking time',
    avgTalkingTime: 'avg talking time',
    feeUnit: 'fee unit',
    unitCount: 'unit count',
    unitPrice: 'unit price',
    totalPrice: 'total price',
    totalFeeCount: 'total fee count',
    ultraShortCount: 'ultra short count',
    ultraShortRatio: 'ultra short ratio',
    shorterCount: 'shorter count',
    shorterRatio: 'shorter ratio',
    normalCount: 'normal count',
    normalRatio: 'normal ratio',
    longerCount: 'longer count',
    longerRatio: 'longer ratio',
    ultraLongCount: 'ultra long count',
    ultraLongRatio: 'ultra long ratio',
    earliestTime: 'earliest time',
    latestTime: 'latest time',
    outboundNo: 'outbound no',
    callResultStatus: 'call result status',
    callResultFilePath: 'call result file path',
    callSysSpeechId: 'call sys speech id',
    speechId: 'speech id',
    speechCode: 'speech code',
    speechName: 'speech name',
    productId: 'product id',
    productCode: 'product code',
    beginTime: 'begin time',
    endTime: 'end time',
    taskGroup: 'task group',
    taskGroupStatus: 'task group status',
    lastTaskGroup: 'last task group',
    taskGroupOrder: 'task group order',
    taskGroupCallNo: 'task group call no',
    lastTaskId: 'last task id',
    currentFilterType: 'current filter type',
    currentFilterContent: 'current filter content',
    autoSwitch: 'auto switch',
    isCallBack: 'is call back',
    isRecall: 'is recall',
    recallType: 'recall type',
    currentRecallTimes: 'current recall times',
    originalRecallTimes: 'original recall times',
    recallTimes: 'recall times',
    recallInterval: 'recall interval',
    recallNumGroup: 'recall num group',
    recallNumSmsSendFlag: 'recall num sms send flag',
    recallNumSmsId: 'recall num sms id',
    filterType: 'filter type',
    filterContent: 'filter content',
    startType: 'start type',
    timedStartTime: 'timed start time',
    excludeRegionOperator: 'exclude region operator',
    changeFlag: 'change flag',
    changeTime: 'change time',
    callerGroupName: 'caller group name',
    failCall: 'fail call',
    notCalled: 'not called'
  },
  zh: {
    ctsn: '客户任务号',
    taskSn: '任务流水号',
    taskType: '任务类型',
    userInfoId: '操作员id',
    userInfoName: '操作员',
    name: '任务名称',
    batchId: '批次id',
    batchOrder: '批次序号',
    year: '年份',
    month: '月份',
    date: '任务日期',
    dateHour: '小时',
    hour: '小时',
    callSys: '引擎类型',
    createType: '创建类型',
    businessScenario: '业务场景',
    industryCode: '行业编号',
    taskClassify: '任务类型',
    status: '任务状态',
    editStatus: '编辑状态',
    statusFailType: '任务状态失败种类',
    failReason: '失败原因',
    isForcibly: '是否强制完成',
    autoDedup: '自动去重',
    smsSendFlag: '是否发送短信',
    hangupSmsId: '短信模板id',
    hangupSmsName: '短信模板名称',
    totalCount: '外呼名单总数',
    formalCount: '正式数据总数',
    testCount: '测试数据总数',
    addDataSuccCount: '添加成功总数',
    addDataFailCount: '添加失败总数',
    processCount: '已经外呼总数',
    cancelCallCount: '及时停播数',
    blackListCount: '黑名单数量',
    dedupCount: '去重数量',
    succSyncCount: '同步完成总数',
    succSyncRate: '同步完成率',
    connCount: '接通总数',
    connRate: '接通率',
    totalTalkingTime: '总通话时长',
    maxTalkingTime: '最大通话时长',
    avgTalkingTime: '平均通话时长',
    feeUnit: '单位',
    unitCount: '单位基数',
    unitPrice: '单价',
    totalPrice: '合计',
    totalFeeCount: '计费总数量',
    ultraShortCount: '超短通时次数',
    ultraShortRatio: '超短通时占比',
    shorterCount: '较短通时次数',
    shorterRatio: '较短通时占比',
    normalCount: '普通通时次数',
    normalRatio: '普通通时占比',
    longerCount: '较长通时次数',
    longerRatio: '较长通时占比',
    ultraLongCount: '超长通时次数',
    ultraLongRatio: '超长通时次数',
    earliestTime: '最早外呼时间',
    latestTime: '最晚外呼时间',
    outboundNo: '外呼线路',
    callResultStatus: '外呼结果文件状态',
    callResultFilePath: '外呼结果文件路径',
    callSysSpeechId: '智能项目流水号',
    speechId: '话术ID',
    speechCode: '话术编码',
    speechName: '话术名称',
    productId: '产品id',
    productCode: '产品code',
    beginTime: '任务开始时间',
    endTime: '任务结束时间',
    taskGroup: '任务组',
    taskGroupStatus: '任务组状态',
    lastTaskGroup: '上一个任务组',
    taskGroupOrder: '任务组序号',
    taskGroupCallNo: '任务组拨打序号',
    lastTaskId: '上一遍任务id',
    currentFilterType: '新任务外呼筛选类型',
    currentFilterContent:
      '新任务外呼筛选规则的内容,可以存储标签或通话结果以,隔开',
    autoSwitch: '自动化开关',
    isCallBack: '是否回传',
    isRecall: '是否重呼',
    recallType: '重呼类型',
    currentRecallTimes: '当前重呼次数',
    originalRecallTimes: '原任务重呼次数',
    recallTimes: '重呼次数',
    recallInterval: '重呼间隔',
    recallNumGroup: '重呼线路',
    recallNumSmsSendFlag: '重呼发送短信标志',
    recallNumSmsId: '重呼发送短信模板',
    filterType: '筛选类型',
    filterContent: '筛选规则的内容,可以存储标签或通话结果以,隔开',
    startType: '启动类型',
    timedStartTime: '定时启动时间',
    excludeRegionOperator: '排除的地区/运营商',
    changeFlag: '是否改良',
    changeTime: '改良变更时间',
    callerGroupName: '主叫组',
    failCall: '外呼失败流水',
    notCalled: '未呼流水'
  }
}
